# Generated by Django 4.2.7 on 2024-02-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='employee_CodePin',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
