# Generated by Django 4.2.7 on 2024-02-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_employe_employee_codepin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(unique=True)),
                ('first_day', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
    ]
