# Generated by Django 4.2.7 on 2024-02-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='first_day',
            field=models.DateField(max_length=20),
        ),
    ]
